// pomodoro/pomodoro-nextjs/src/views/register/RegisterVerifying.tsx
import classes from "classnames"
import { observer } from "mobx-react-lite"
import { RegisterState as State } from "./RegisterState"
import { Verifying } from "./Verifying"
import Link from "../../components/Link"

export default observer(function RegisterVerifying({
  state,
  verifying,
}: {
  state: State
  verifying: Verifying
}) {
  return (
    <div className="text-xm overflow-x-auto py-1">
      <div className="flex flex-col items-center text-center">
        <div className="py-2 text-xl font-bold">
          {state.lang.zh && <div>等待邮件注册确认</div>}
          {state.lang.en && <div>Awaiting Register Email Confirmation</div>}
        </div>

        <div className="py-1 text-lg">
          {state.lang.zh && (
            <div>
              已向 <b>{verifying.email}</b> 发送了邮件
            </div>
          )}
          {state.lang.en && (
            <div>
              We just sent an email to <b>{verifying.email}</b>
            </div>
          )}
        </div>

        <div className="py-1 text-lg">
          {state.lang.zh && (
            <div>
              确认前，请比对 <b>识别码</b>：
            </div>
          )}
          {state.lang.en && (
            <div>
              Before verifying, please compare the <b>confirmation code</b>:
            </div>
          )}
        </div>

        <div className="py-2 text-lg">
          <p
            className={classes(
              "border-4 py-1 px-2 font-black",
              `border-${state.theme.name}-300 bg-${state.theme.name}-500`
            )}
          >
            {verifying.confirmation_code}
          </p>
        </div>

        <button
          className={classes(
            "my-2 font-sans font-bold",
            `text-${state.theme.name}-50 hover:text-${state.theme.name}-200`
          )}
        >
          {state.lang.zh && <div>撤销</div>}
          {state.lang.en && <div>REVOKE</div>}
        </button>
      </div>
    </div>
  )
})

// readonlylink/pages/auth/RegisterVerifying.vue
<template>
  <div class="text-xm overflow-x-auto py-1">
    <div class="flex flex-col items-center text-center">
      <Multilingual class="py-2 text-xl font-bold">
        <template #zh> 等待邮件注册确认 </template>
        <template #default> Awaiting Register Email Confirmation </template>
      </Multilingual>

      <Multilingual class="py-1 text-lg">
        <template #zh>
          已向 <b>{{ email }}</b> 发送了邮件
        </template>
        <template #default>
          We just sent an email to <b>{{ email }}</b>
        </template>
      </Multilingual>

      <Multilingual class="py-1 text-lg">
        <template #zh> 确认前，请比对 <b>识别码</b>： </template>
        <template #default>
          Before verifying, please compare the <b>confirmation code</b>:
        </template>
      </Multilingual>

      <div class="py-2 text-lg">
        <p class="border-4 border-gray-200 bg-gray-100 py-1 px-2 font-black">
          {{ confirmation_code }}
        </p>
      </div>

      <button
        class="my-2 font-sans font-bold text-gray-400 hover:text-gray-900"
        @click="revoke()"
      >
        <Multilingual>
          <template #zh> 撤销 </template>
          <template #default> REVOKE </template>
        </Multilingual>
      </button>
    </div>
  </div>
</template>

<script>
import PageLayout from "../../components/layouts/page-layout/PageLayout.vue"
import RegisterLayout from "./RegisterLayout.vue"

export default {
  layout: [PageLayout, RegisterLayout],
}
</script>

<script setup>
import { ref, onMounted } from "vue"
import axios from "axios"
import ty from "@xieyuheng/ty"
import { Inertia } from "@inertiajs/inertia"
import { createProps } from "../../ut/create-props"
import { useConfig } from "../../composables/config"

import Multilingual from "../../components/atoms/Multilingual.vue"

const config = useConfig()

const props = defineProps(
  createProps({
    email: ty.string(),
    confirmation_code: ty.string(),
    links: ty.object({
      verify: ty.string(),
      revoke: ty.string(),
    }),
  })
)

const polling = ref(null)

onMounted(() => {
  polling.value = window.setInterval(async () => {
    const { data } = await axios.get(props.links.verify)
    if (data) {
      const { username } = data
      clearPolling()
      Inertia.get(
        `/projects/${username}`,
        {},
        {
          replace: true,
          preserveState: true,
        }
      )
    }
  }, 3000)
})

function clearPolling() {
  if (polling.value !== null) {
    clearInterval(polling.value)
  }
}

async function revoke() {
  clearPolling()
  await axios.get(props.links.revoke)
  Inertia.get(
    `/register`,
    {},
    {
      replace: true,
      preserveState: true,
    }
  )
}
</script>
